### ISSUE TITLE
Consider releasing 2.0.0

### ISSUE THREAD

**Issue by silverwind** [pillarjs/router#105]
I've been using [2.0.0-beta.1](https://www.npmjs.com/package/router/v/2.0.0-beta.1) for a long time without issues. Are there any blockers left for a 2.0.0 release?

**Comment by silverwind** [comment]
Nevermind, I see there is https://github.com/pillarjs/router/pull/60.

**Comment by dougwilson** [comment]
I plan to get the last bits pulled in this weekend, actually, as you are wondering. I am removing myself from a lot of different time consuming packages to free up my time on the packages I care about lile this one.

**Comment by silverwind** [comment]
Yes, this package is definitely a "gem" from the express toolkit :)
