### ISSUE TITLE
1.0 release date

### ISSUE THREAD

**Issue by scottcorgan** [pillarjs/router#11]
Curious on the timeline for non-beta release. In the middle of a refactor and this module is at the heart of it.

**Comment by scottcorgan** [comment]
Not to bug, but wanted to ask if there's any update on removing the beta tag from NPM?

**Comment by dougwilson** [comment]
Yea, I had forgotten about it and when I went to publish the other day, I felt bad and was hoping you didn't notice. Sorry :)! I really wanted to get the last tests for param handling (mainly so there is less chance of breaking it, haha). I feel good enough right now hat for you, I'm going to _promise_ I'm going to publish 1.0.0 tonight, even if I didn't completely finish the tests.

**Comment by scottcorgan** [comment]
Sounds good. Was just curious. I'm impressed you're able to keep up with
all the repos you commit to.

**Comment by dougwilson** [comment]
haha, it's no problem :) I want this to be 1.0.0 as well :)

**Comment by dougwilson** [comment]
BTW, @scottcorgan , let me know if you have any thoughts on this request: https://github.com/strongloop/express/issues/2483

**Comment by dougwilson** [comment]
Your 1.0.0 has been published :)

**Comment by scottcorgan** [comment]
I appreciate that. Important people will feel better without the beta word. Thank you.

**Comment by dougwilson** [comment]
> Important people will feel better without the beta word.

Definitely understandable :) Plus you now have the option to not lock against a single version; you could potentially let the patch float since we've now made a SemVer promise ;)

**Comment by scottcorgan** [comment]
Sound great! Thanks for being so responsive.
