### ISSUE TITLE
1.x Branch

### ISSUE THREAD

**Issue by Phillip9587** [pillarjs/router#146]
We should switch this for `1.x`. And while I was making this comment I realized we did not create the `1.x` branch, so we should also create that I think.

_Originally posted by @wesleytodd in https://github.com/pillarjs/router/pull/143#discussion_r1836715985_

@wesleytodd If you create the branch i can backport some changes to the CI Pipeline to the 1.x branch.

**Comment by wesleytodd** [comment]
done: https://github.com/pillarjs/router/tree/1.x
