### ISSUE TITLE
Cannot find module 'router/engine' error

### ISSUE THREAD

**Issue by jewelsjacobs** [pillarjs/router#16]
Hi there!

I'm using a module that has this module as a dependency which I believe is causing that module to crash.

Here's the details:
https://github.com/mulesoft-labs/osprey-router/issues/1

I think its due to an unresolved path in index.js which I can't find in your repo.  Your repo code seems totally different then the code in the npm module. :)

**Comment by dougwilson** [comment]
Hi! That module does not actually use this module, but rather a fork of it. Check out what's in the package.json:

        "router": "git://github.com/blakeembrey/router#router-engine"
