### ISSUE TITLE
Continuation control flow from middleware

### ISSUE THREAD

**Issue by h2non** [pillarjs/router#19]
Currently the router only discern between path based pattern matching.

In some cases it could be useful to ignore a matched route in the case that during in the middleware dispatch process, providing an extra layer of control flow. 

To give you a simple example:
 ```js
router.use('/users', function (req, res, next) {
  if (req.headers.version === '1.0') {
    // Ignore the route and continue with the request matching process with other routes
    return next.continue()
  }
  // Perform mad science here with the route as usual
  next()
})
```

**Comment by dougwilson** [comment]
Hi! Can you expand on your example a little bit :)? It's not clear to me where `next.continue()` would go and how it's different from `next()` or `next('route')`.

**Comment by h2non** [comment]
The idea is simply try to continue with the route matching process, instead of running the current matched route (e.g: `/users` in the above example).

As far as I can understand, calling `next('error')` will terminate the middleware cycle stoping calling the pending ones and reaching the final handler to do whatever it should do in case of error, like for instance write the response with an error, but this doesn't allow you to re-start the route matching process trying to match the next route after `/users`, for instance I could configure another one with the same method and path, but for a different purpose.

Probably my proposal is a sort of workaround to achieve a missing feature like providing a more powerful matching based on multiple request params, such as HTTP headers. E.g:
```js
route.use('/users', /* run only if match header */ { 'Version': '1.0' }, middleware)
```

**Comment by dougwilson** [comment]
Gotcha. To me, you are simply describing `next('route')` (where you pass a special string, `'route'` as the argument to next):
```js
// this will not run "middleware" if req.headers.version is not 1.0
route.use('/users', onlyIfVersion1, middleware)
route.use('/users', ..) // this is where next('route') jumps you to

function onlyIfVersion1(req, res, next) {
  if (req.headers.version !== '1.0') return next('route')
  next()
}
```

**Comment by dougwilson** [comment]
You can find more information about `next('route')` in the Express 4.x docs: http://expressjs.com/guide/routing.html#route-handlers

**Comment by h2non** [comment]
[Got it](https://github.com/pillarjs/router/blob/master/lib/route.js#L109)! 
That would be enough. Thanks

**Comment by dougwilson** [comment]
Here is an example of using what is currently in this module that seems like it fits your use-case exactly:
```js
route.use('/users', /* run only if matches the header */ requireHeadersMatch({ 'Version': '1.0' }), middleware)
route.use('/users', /* run only if matches the header */ requireHeadersMatch({ 'Version': '2.0' }), middleware)

function requireHeadersMatch(headers) {
  return function (req, res, next) {
    for (var k in headers) {
      if (req.headers[k.toLowerCase()] !== headers[k]) return next('route')
    }
    next()
  }
}
```

**Comment by dougwilson** [comment]
> Got it! That would be enough. Thanks

Cool :) Let me know if you need anything! I was actually just playing around with your `rocky` earlier this week :)

**Comment by h2non** [comment]
Thanks for the snippet. My example above was just representative to explain the thing, but the obvios way to do that is via middleware, indeed I created a [tiny middleware module](https://github.com/h2non/http-version) which does the same.

Regarding to `rocky`, I'm happy to read that :D. It's still young, but I'm working in a new version with interesting features. Feel free to give any kind of feedback, I'll appreciate it.
