### ISSUE TITLE
Ability to exit entire router

### ISSUE THREAD

**Issue by blakeembrey** [pillarjs/router#20]
From https://github.com/strongloop/express/issues/2241, add the ability to skip the rest of the router. I could have sworn I commented on the issue, but I can't find it anyway.

Use case: Automatically setting up validation middleware (from RAML). I don't want two conflicting routes to run, so exiting on the first handled would be preferable to potentially buggy and confusing behaviour.

**Comment by dougwilson** [comment]
Also additional discussion in https://github.com/strongloop/express/pull/2371
