### ISSUE TITLE
Ability to unregister routes

### ISSUE THREAD

**Issue by h2non** [pillarjs/router#21]
Worth saying that this scenario is very not too much common, however in certain specific cases would be handy. Probably this responsibility should be provided natively by the router.

So the idea may be exposing a method to simply remove `Layer` instances from the route `stack` would be nice. Since `Layer` is totally encapsulated as internal implementation detail, it's agnostic to the API consumer, so in terms of querying to find the proper route to remove, it would mimic the natural router matching pipeline (method, regex path).

**Comment by dougwilson** [comment]
The design of the router makes this almost impossible, but if you're willing to start working on a PR to start a discussion off, that would be welcome and the best way to get something like this moving :)
