### ISSUE TITLE
Ability to specify query parser in /router

### ISSUE THREAD

**Issue by sebilasse** [pillarjs/router#27]
I would find it very useful for larger ecosystems or app compose to specify the
`query parser` option at router level as well.

**Comment by blakeembrey** [comment]
@sebilasse Could you elaborate? There's no "query parser" option in the router, and to specify one you can just use it as middleware before everything else. Or am I missing something with the request?

**Comment by sebilasse** [comment]
sorry. Let me explain. I was talking about the [express .app level](http://expressjs.com/4x/api.html#app.set) and forgot that this is an independent project. 
First of all I am doing it exactly as you described.
My snippet for [RQL](https://github.com/kriszyp/rql) is
```js
app.set('query parser', function(qStr){
  return (typeof qStr != 'string' || !qStr.length) ? {} : rql.parseQuery(qStr);
});
```
where rql. is the above linked parser :

This is merely a feature request if we could specify the "shortcuts" like express does 
e.g. `"simple", "qs", "rql"`
and ship the 3 parsers with the package.json ...

**Comment by dougwilson** [comment]
Right. All of those mechanics are all part of Express. I think what you are asking for is the already open issue in Express https://github.com/strongloop/express/issues/2524 , which basically is asking for setting to be per-router as well as per-app.

The problem with the request is that the having of settings is actually the exact thing that separates what an app is vs what a router is. You can think of an app is a "router with settings".
