### ISSUE TITLE
How to make one gate router?

### ISSUE THREAD

**Issue by yozawiratama** [pillarjs/router#45]
I mean i just need one router but it can be a gate to all route or path. for example : 

path : `/`
```
router.get('/', function (req, res) {
  res.statusCode = 200
  res.setHeader('Content-Type', 'text/plain; charset=utf-8')
  res.end('no path or param')
})
```

path : `/user`
```
router.get('/', function (req, res) {
  var parh = //someway i can get user as path param
  res.statusCode = 200
  res.setHeader('Content-Type', 'text/plain; charset=utf-8')
  res.end('path : user, but has no param')
})
```

path : `/user/1`
```
router.get('/', function (req, res) {
  var parh = //someway i can get user as path param
  var param = //someway i can get 1 as param
  res.statusCode = 200
  res.setHeader('Content-Type', 'text/plain; charset=utf-8')
  res.end('path : user and param : 1')
})
```

and all of that only with `/` route as one gate route. in inner handler i wish i can proccess path and param as i want.

**Comment by wesleytodd** [comment]
Is there a reason you wouldn't just use the same middleware function on multiple routes?

```javascript
var myHandler = function (req, res) {
  // do stuff...
  if (req.params.id) { /* ... */ }
};
router.get('/', myHandler);
router.get('/user', myHandler);
router.get('/user/:id', myHandler);
```

**Comment by dougwilson** [comment]
Hi @yozawiratama, I'm really not 100% sure what you are even asking, but based on your example and the comments in them, what it sounds like you want is the following:
```js
router.get('/:path?/:param?', function (req, res) {
  res.statusCode = 200
  res.setHeader('Content-Type', 'text/plain; charset=utf-8')

  if (req.params.path) {
    if (req.params.param) {
      res.end('path : ' + req.params.path + ' and param : ' + req.params.param)
    } else {
      res.end('path : ' + req.params.path + ', but has no param')
    }
  } else {
    res.end('no path or param')
  }
})
```

**Comment by yozawiratama** [comment]
@dougwilson thanks dude, that's what i want. i try to understand how framework works with their own router. 👍

**Comment by wesleytodd** [comment]
FWIW, generally a bunch of nested `if` statements are hard to read and maintain.  If you can break up your application into middleware that do common functionality and handlers that to the specific responses for your application it is a much better architecture than a single handler function.  

This is not really the place to get into architecture discussions, but Express is designed around middleware composability.  Not to counter what Doug said, especially seeing that he is the most knowledgeable about express that there is, but I would recommend looking into a better architecture for your application than a single handler function.  Maybe look here: http://expressjs.com/en/guide/using-middleware.html

**Comment by dougwilson** [comment]
Hi @wesleytodd, yes, it is not a good pattern to use, but at the same time, if the user wants to do it, I don't really care :) In fact, when I was first trying to figure out the question, one of my original answer drafts was going to say "why even bother using this module?" but I realized that they could use this module if really wanted to.
