### ISSUE TITLE
Multiple slashes in a path

### ISSUE THREAD

**Issue by sebilasse** [pillarjs/router#46]
`http://example.com/a//b/c` does not match the route for `/a/b/c`.
I think it should if `strict: false` ...

**Comment by DavidTPate** [comment]
A few things with this:

* This would break backwards compatibility in terms of functionality as `strict` is defined explicitly as "When `false` trailing slashes are optional".
* The URI `http://example.com/a//b/c` is an invalid URI as between slashes it is required to have a non-zero segment, which that does not.
* This seems like it would be something that should be handled by the consumer of `router` to sanitize the paths if desired and not a responsibility of the router.

**Comment by sebilasse** [comment]
@DavidTPate Agreed to. 
About •2) I am not sure : Off course it is an invalid URL but probably the most seen one.
It occurs in so many code in the wild that missing or empty strings as segments are not treated well.
About •3) Apache treats multiple slashes as a single slash by default an Nginx gives you `merge_slashes`.

**Comment by DavidTPate** [comment]
You could handle it via Userland middleware @sebilasse. In `restify` for example they have their [plugins](https://github.com/restify/plugins#usage) which are just middleware functions. If you were to use the `sanitizePath()` middleware in your Express app near prior to the routing then I expect it would work as you expect.

**Comment by sebilasse** [comment]
@DavidTPate I think these are helpful informations for everyone. Will have a look @ `sanitizePath()`. FYI: I am currently extending this router to support JSON Schema.

**Comment by HarshithaKP** [comment]
@sebilasse Is this still an issue for you ?

**Comment by sebilasse** [comment]
No.
