### ISSUE TITLE
Custom finalhandler 

### ISSUE THREAD

**Issue by ansarizafar** [pillarjs/router#61]
How can I write a custom finalhandler to handle route not found(404) and other errors?

**Comment by dougwilson** [comment]
When you invoke router you have to provide the callback. That callback is where you would get an error if there is an error or no error if it would be 404. Just write whatever logic you like there :)

**Comment by dougwilson** [comment]
The callback doesn't get req and res, just err.

    router(req, res, (err) => ...)

**Comment by ansarizafar** [comment]
Router examples in readme show that finalhandler invoked like this
```
var server = http.createServer(function(req, res) {
  router(req, res, finalhandler(req, res))
})
```
How can we send response without res in callback?

**Comment by dougwilson** [comment]
This is because finalhandler is just a factor that returns a function as I put above. You have access to req and res in your closure.

**Comment by dougwilson** [comment]
Example:

    router(req, res, (err) => res.end('oops!'))

**Comment by ansarizafar** [comment]
It worked. Thanks
