### ISSUE TITLE
nested routers should receive params from parent

### ISSUE THREAD

**Issue by TrejGun** [pillarjs/router#64]
Let say i have tree of files and each of then returns router

```js
// level2.js
const router = Router()
router.route("/user/:id")
.get((req, res) => {})

// level1.js
import level2 from "level2";
const router = Router()

function createRegExpParameter(re, name) {
	return (request, response, next, val) => {
		if (re.test(String(val))) {
			next();
		} else {
			next(new Error("invalid param"));
		}
	};
}
router.param("id", createRegExpParameter(/[0-9]+/, "id"));

router.use("/api", level2)

// server.js
import level1 from "level1";
const app = express()
app.use(level1)
```

in this case when i access `/api/user/1` id won't be validated, so it would be good to pass param from top most router (or app) down to bottom most

**Comment by wesleytodd** [comment]
Hi @TrejGun, I am having trouble understanding the code you have above (maybe you meant to have the route be `/user/:id`?).  But the `router` in `level1.js` cannot know about the route defined in `level2.js`, as it is not processed until the control is handed over.  

If I understand what you are asking correctly, you would be tightly coupling the sub router to the parent router, which is not a recommended way to architect your application.  I believe you probably should not be creating multiple routers like this and instead have these sections use the same router.

**Comment by TrejGun** [comment]
so you mean i have to pass my `app` instead?

```js
// level2.js
export default (app, prefix) => {
	app.route(`${prefix}/user/:id`)
		.get((req, res) => {})
}
// level1.js
import level2 from "level2";

function createRegExpParameter(re, name) {
	return (request, response, next, val) => {
		if (re.test(String(val))) {
			next();
		} else {
			next(new Error("invalid param"));
		}
	};
}

export default app => {
	app.param("id", createRegExpParameter(/[0-9]+/, "id"));
	level2(app, "/api")
}

// server.js
import level1 from "level1";
const app = express()
level1(app);

```

this what i'm trying to avoid because  eventually i will end up with 
```js
app.route(`${prefix1}/${prefix2}/${prefix3}/user/:id`)
```

**Comment by wesleytodd** [comment]
That would be one way to a solution, but if you are planning on nesting things that deeply it might be better to just create a shared validation library which all the submodules use for the `id` validation:

```javascript
module.exports = function validateId (req, res, next, val) {
  if (/[0-9]+/.test(val)) {
    next();
  } else {
    next(new Error("invalid param"));
  }
};
```

This avoids tightly coupling the routers, but still enables a simple validation mechanism.

FWIW, I have been focusing on the problem in general, but if all you really want to do is ensure a route portion matches a regex you can do it directly in the router, see:  https://github.com/pillarjs/path-to-regexp#custom-matching-parameters

**Comment by TrejGun** [comment]
`validateId ` that is what i'm currently doing

```js
// router-validators.js
function createRegExpParameter(re) {
	return (request, response, next, val) => {
		if (re.test(String(val))) {
			next();
		} else {
			next(new Error("invalid param"));
		}
	};
}

export const validateId = createRegExpParameter(/[0-9]+/));

// level2.js
import {validateId} from "router-validators";
const router = Router()
router.use(validateId);
router.route("/user/:id")
	.get((req, res) => {})

// level1.js
import level2 from "level2";
const router = Router()
router.use("/api", level2)

// server.js
import level1 from "level1";
const app = express()
app.use(level1)
```

and i in the last sentence you suggest to do in-place validation like

```
// router-params
export const id = ":id(/[0-9]+/)";

// level2.js
import {id} from "router-params";
const router = Router()
router.use(validateId);
router.route(`/user/${id}`)
	.get((req, res) => {})
```

am i right?

**Comment by wesleytodd** [comment]
Yeah, the last solution will end in a `404` if `id` is not a number.  If that is alright for your use case then that is probably the best way.

**Comment by TrejGun** [comment]
thanks, that helps
