### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by k-raph** [pillarjs/router#82]
Hello everyone. I was wondering if there could be a new release for this awesome library as it seems it's on a death line. We could add other features as by example names routes and url generation. This could be "easy" I guess with latest releases of "path-to-regexp" library. What do you think about it??

**Comment by dougwilson** [comment]
There are new releases, even the alpha of the 2.0. Perhaps it would help if you could clarify what, specifically,  you are looking for by making a specific feature request or bug report, so we can understand what we need to do in a specific way :+1:

**Comment by k-raph** [comment]
Thank you for you reply. The main feature I'd request is url generation. Coming from a PHP env, I find it useful to have this as it help generate urls in views. And I'll check the 2.0 alpha release too. Great thanks.

**Comment by dougwilson** [comment]
For the url generation request, please open a new issue for that and be as detailed as possible as to what you want. Besides the words "url generation", I don't know what that means to you and what it should do, how it would look like if implemented here, etc. Please be sure to include enough details so we can understand the feature.

**Comment by k-raph** [comment]
Okay thanks.
