### ISSUE TITLE
Promise support for `router.param`

### ISSUE THREAD

**Issue by jonchurch** [pillarjs/router#91]
This is a reminder to myself (or anyone else) to implement this and give a smooth upgrade path to users of `express-async-errors`

https://github.com/davidbanham/express-async-errors/issues/28

**Comment by jonchurch** [comment]
@dougwilson Can you assign this issue to me? I don't seem to have perms to do that in this repo.

**Comment by wesleytodd** [comment]
@jonchurch are you still interested in working on this? If you are, I would love to figure out how we can land holistic promise support before `router@2` happens. I have this one in flight from a while back as well: https://github.com/pillarjs/router/pull/75

**Comment by jonchurch** [comment]
Yeah Im interested. Need to dig up old stuff but I had reached out to the maintainer if a popular package that monkey patched router with promise support. 

If I can coordinate a release there to not crash when people use it with a native promise supporting router that would be great

**Comment by jonchurch** [comment]
@wesleytodd oh this merge in 2021 I didn't realize https://github.com/pillarjs/router/pull/92
