### ISSUE TITLE
Multiple param middlewares order

### ISSUE THREAD

**Issue by nklhrstv** [pillarjs/router#99]
The README says about param middlewares that they are put in the same stack as `.use`.
Ive expected the order of calling to be the same.
In the following example with `param` the logs are like: 1, 3, 2
```javascript
middleware.param('name', async (req, res, next) => {
    console.log(1);
    next();
});
middleware.get('/:name.:ext', async (req, res, next) => {
    console.log(2);
    res.end();
    next();
});
middleware.param('name', async (req, res, next) => {
    console.log(3);
    next();
});
```

In the following example with `use` the logs are like: 1, 2, 3
```javascript
middleware.use(async (req, res, next) => {
    console.log(1);
    next();
});
middleware.get('/:name.:ext', async (req, res, next) => {
    console.log(2);
    res.end();
    next();
});
middleware.use(async (req, res, next) => {
    console.log(3);
    next();
});
```

Is that an expected behavior or a bug ?

**Comment by rodion-arr** [comment]
Hi @nklhrstv! Is this comment addresses your question?
https://github.com/expressjs/express/issues/4479#issuecomment-740622791

**Comment by nklhrstv** [comment]
@rodion-arr Yes. Thank you!
